blogsite/urls.py
from django.conf.urls import patterns, url, include
from blog import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', views.BlogListView.as_view(), name='home'),
    url(r'^login/$', views.AdminLoginView.as_view(), name='admin_login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^admin/$', views.AdminView.as_view(), name='admin'),
    url(r'^admin/edit/$', views.EditView.as_view(), name='edit'),
    url(r'^admin/settings/$', views.SettingsView.as_view(), name='settings'),
    url(r'^admin/uploadimg/$', views.UploadImageView.as_view(), name='uploadimg'),
    url(r'^admin/imginfo/$', views.ImageInfoView.as_view(), name='imginfo'),
    url(r'^tag/(?P<tag>.+)/$',
        views.BlogListView.as_view(), name='tag'),
    url(r'^category/(?P<slug>.+)/$',
        views.BlogListView.as_view(), name='category'),
    url(r'^date/(?P<year>\d{4})(?P<month>\d{2})/$',
        views.BlogListView.as_view(), name='date'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>.+)/$',
        views.BlogView.as_view(), name='blog'),
    url(r'^feed/$', views.RSSFeed(), name='feed'),
    # Examples:
    # url(r'^$', 'blogsite.views.home', name='home'),
    # url(r'^blogsite/', include('blogsite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/django/', include(admin.site.urls), name='admin_django'),
)

from blogsite import settings
if hasattr(settings, 'DEBUG') and settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

blog/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import pre_delete
from django.dispatch import receiver


class Setting(models.Model):
    name = models.CharField(max_length=255, unique=True)
    value = models.CharField(max_length=1024, blank=True, null=True)

    def __unicode__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    rank = models.IntegerField(blank=True, null=True, default=0)

    def __unicode__(self):
        return self.name


class Blog(models.Model):
    slug = models.SlugField(max_length=255, editable=False, unique=True)
    title = models.CharField(max_length=255)
    date_create = models.DateTimeField(auto_now_add=True)
    date_modify = models.DateTimeField(auto_now=True)
    body_html = models.TextField()
    body_raw = models.TextField(blank=True, null=True)
    RAW_FORMAT_CHOICES = (
        ('html', 'HTML Format'),
        ('md', 'Markdown'),
        ('album', 'Photo Album'),
    )
    raw_format = models.CharField(max_length=10, choices=RAW_FORMAT_CHOICES, default='html')
    active = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    STATUS_CHOICES = (
        ('public', 'Post'),
        ('draft', 'Save as Draft'),
        ('delete', 'Delete!'),
        ('private', 'Private Only!'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='public')
    category = models.ForeignKey(Category, blank=True, null=True)

    def __unicode__(self):
        return self.title

    def save(self, **kwargs):
        def alloc_slug(title):
            slug = title.replace(' ', '-')
            if Blog.objects.filter(slug=slug):  # found slug conflict
                slug = slug + datetime.now().strftime("_%y%m%d-%H%M%S")
            return slug

        def raw2html(raw, type):
            def md2html(raw):
                import markdown
                md = markdown.Markdown(extensions=['fenced_code'])
                return md.convert(raw)

            def album2html(raw):
                from bs4 import BeautifulSoup

                soup = BeautifulSoup(raw)
                desc = soup.find(id='album-desc')

                images_orig = soup.find(id='album-images')
                coverid = images_orig.get('data-cover')
                images = soup.new_tag('div', id='album-images')
                for imgtag in images_orig.find_all(['img']):
                    try:
                        idx = imgtag.get('data-id')
                        img = Image.objects.get(idx=idx)
                        self.image_set.add(img)
                        imgtag['src'] = img.thumb_url
                        imgtag['alt'] = img.desc if img.desc else ''
                        imgtag['data-src'] = img.img_url
                        images.append(imgtag)
                    except:  # ignore illegal img
                        pass

                divcover = soup.new_tag('div', id='album-cover')
                try:
                    coverimg = images.find(lambda tag: tag.get('data-id') == coverid)
                    import copy
                    divcover.append(copy.deepcopy(coverimg))
                except:
                    pass

                return '\n'.join(map(lambda div: div.prettify(),
                                     [divcover, desc, images]))

            if type == 'md':
                html = md2html(raw)
            elif type == 'html':
                html = raw
            elif type == 'album':
                html = album2html(raw)
            return html

        if not self.id:  # new object here
            self.slug = alloc_slug(self.title)
        self.body_html = raw2html(self.body_raw, self.raw_format)

        self.full_clean()
        models.Model.save(self, **kwargs)

    def update_tags(self, tag_list):
        if not self.id:  # new here, need to save before update m2m fields
            self.save()
        tags_new = set(
            map(lambda n: Tag.objects.get_or_create(name=n)[0], tag_list))
        tags_old = set(self.tags.all())
        for tag in tags_old - tags_new:
            self.tags.remove(tag)
        for tag in tags_new - tags_old:
            self.tags.add(tag)

    @models.permalink
    def get_absolute_url(self):
        return ('blog', (), {
            'year': self.date_create.strftime('%Y'),
            'month': self.date_create.strftime('%m'),
            'slug': self.slug})


class Image(models.Model):
    idx = models.AutoField(primary_key=True)
    img = models.ImageField(upload_to='image/', blank=True, null=True)
    _img_url = models.URLField(blank=True, null=True)
    thumb = models.ImageField(upload_to='image/thumb/', blank=True, null=True)
    _thumb_url = models.URLField(blank=True, null=True)

    desc = models.TextField(blank=True, null=True)

    STATUS_CHOICES = (
        ('created', 'obj has been just created'),
        ('uploaded', 'image has been uploaded'),
        ('updated', 'related blog has been updated'),
        ('invalid', 'url is invalid'),
    )
    status = models.CharField(max_length=15, default='created')
    active = models.BooleanField(default=True)

    blog = models.ForeignKey(Blog, blank=True, null=True)

    def __unicode__(self):
        return str(self.idx)

    def _get_img_url(self):
        return self._img_url if self._img_url else self.img.url

    def _set_img_url(self, url):
        self._img_url = url

    img_url = property(_get_img_url, _set_img_url)

    def _get_thumb_url(self):
        if self._thumb_url:
            url = self._thumb_url
        elif self.thumb:
            url = self.thumb.url
        else:
            url = self.img_url
        return url

    def _set_thumb_url(self, url):
        self._thumb_url = url

    thumb_url = property(_get_thumb_url, _set_thumb_url)


# According django doc, delete() may not be called when
# doing objects.delete(), so need to register a hanlder
# to delete related files before Image.delete()
@receiver(pre_delete, sender=Image)
def image_delete_handler(sender, **kwargs):
    image = kwargs.get('instance')
    for f in [image.img, image.thumb]:
        if f:
            f.delete(save=True)


# admin hook
from django.contrib import admin

admin.site.register(Setting)
admin.site.register(Tag)
admin.site.register(Category)
admin.site.register(Blog)
admin.site.register(Image)

blog/views.py
# -*- coding: utf8 -*-
# Create your views here.
import json
from django import http
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse, resolve
#from django.core import exceptions
from django.views.generic import FormView, DetailView, ListView
from django.contrib.syndication.views import Feed
from models import Blog, Tag, Setting, Image, Category
from forms import AdminUserForm, BlogForm


class AdminLoginView(FormView):
    form_class = AdminUserForm
    template_name = 'blog_admin/login.html'
    success_url = '/admin/'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return self.render_to_response({'form': form})

    def post(self, request, *args, **kwargs):
        form = AdminUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_superuser and user.is_active:
                    login(request, user)
                    return http.HttpResponseRedirect(self.get_success_url())
        msg = "Invalid username or password, please try again."
        return self.render_to_response({'form': form, 'msg': msg})


def logout_view(request):
    logout(request)
    return http.HttpResponseRedirect('/')


def check_permission(cls):
    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if user and user.is_authenticated() and user.is_superuser:
            return super(self.__class__, self).dispatch(request, *args, **kwargs)
        else:
            return http.HttpResponseRedirect(reverse("admin_login"))

    cls.dispatch = dispatch
    return cls


@check_permission
class AdminView(ListView):
    model = Blog
    queryset = Blog.objects.exclude(status='delete').order_by("-date_create")
    template_name = 'blog_admin/admin.html'
    paginate_by = 10


@check_permission
class UploadImageView(FormView):
    def post(self, request, *args, **kwargs):
        result = {}
        for name in request.FILES:
            fobj = request.FILES[name]
            fname = fobj.name
            try:
                image = Image()
                image.img.save(fname, fobj)
                image.save()
                result[fname] = {
                    'status': True,
                    'idx': image.idx,
                    'img_url': image.img_url,
                    'thumb_url': image.thumb_url,
                }
            except Exception, e:
                result[fname] = {
                    'status': False,
                    'msg': str(e),
                }
        return http.HttpResponse(json.dumps(result))


@check_permission
class ImageInfoView(FormView):
    def post(self, request, *args, **kwargs):
        reqs = json.loads(request.read())
        response = {}
        for idx in reqs:
            req = reqs[idx]
            try:
                if req.get('action') == 'read':
                    img = Image.objects.get(idx=idx)
                    result = {
                        'status': True,
                        'img_url': img.img_url,
                        'thumb_url': img.thumb_url,
                        'desc': img.desc,
                    }
                elif req.get('action') == 'write':
                    Image.objects.filter(idx=idx).update(desc=req.get('desc'))
                    result = {'status': True}
                elif req.get('action') == 'del':
                    Image.objects.filter(idx=idx).delete()
                    result = {'status': True}
                else:
                    result = {
                        'status': False,
                        'msg': 'wrong action code, should be "read" or "write"'
                    }
            except Exception, e:
                result = {
                    'status': False,
                    'msg': str(e),
                }
            response[idx] = result
        return http.HttpResponse(json.dumps(response))


@check_permission
class EditView(FormView):
    '''
    kwargs for url
    * new post: /
    * edit existig post: /?pk=primary_key
    '''
    form_class = BlogForm
    template_name = 'blog_admin/edit.html'
    success_url = '/admin/'

    @staticmethod
    def _get_blog(pk):
        ''' when pk is 0, return empty Blog() '''
        try:
            return Blog.objects.get(pk=pk) if pk else Blog()
        except Blog.DoesNotExist:
            raise http.Http404

    def get(self, request, *args, **kwargs):
        pk = int(request.GET.get('pk', 0))
        blog = self._get_blog(pk)
        return self.render_to_response({'blog': blog,
                                        'pk': pk,
                                        'tags': Tag.objects.all(),
                                        'category': Category.objects.all()})

    def post(self, request, *args, **kwargs):
        pk = int(request.REQUEST.get('pk', 0))
        blog = self._get_blog(pk)
        form = self.form_class(request.POST)
        if form.is_valid():
            form.saveto(blog)
        else:
            return self.render_to_response({'blog': blog, 'pk': pk, 'tags': Tag.objects.all()})
        return http.HttpResponseRedirect(self.get_success_url())


@check_permission
class SettingsView(FormView):
    form_class = Setting
    template_name = 'blog_admin/settings.html'
    success_url = '/admin/'

    def get(self, request, *args, **kwargs):
        return self.render_to_response({})

    def post(self, request, *args, **kwargs):
        for name, value in request.POST.items():
            setting, created = Setting.objects.get_or_create(name=name)
            setting.value = value
            setting.save()
        return http.HttpResponseRedirect(self.get_success_url())


class BlogView(DetailView):
    model = Blog
    template_name = 'blog.html'
    context_object_name = 'blog'
    slug_url_kwarg = 'slug'


class BlogListView(ListView):
    template_name = 'index.html'
    context_object_name = 'blogs'
    paginate_by = 6

    def get_queryset(self):
        if not self.queryset:
            try:
                path = self.request.path
                view_name = resolve(path).url_name
                context = dict(self.kwargs)
                context['path'] = path
                context['view_name'] = view_name
                self._context = context
                if view_name == 'home':
                    queryset = Blog.objects.all()
                elif view_name == 'tag':
                    name = self.kwargs.get('tag')
                    tag = Tag.objects.get(name=name)
                    queryset = tag.blog_set.all()
                elif view_name == 'category':
                    slug = self.kwargs.get('slug')
                    category = Category.objects.get(slug=slug)
                    queryset = category.blog_set.all()
                elif view_name == 'date':
                    year = int(self.kwargs.get('year', 0))
                    month = int(self.kwargs.get('month', 0))
                    queryset = Blog.objects.filter(date_create__year=year,
                                                   date_create__month=month)
                else:
                    raise LookupError
            except:
                raise http.Http404
            self.queryset = queryset.filter(status='public').order_by("-date_create")
        return self.queryset

    def get_context_data(self, **kwargs):
        context = kwargs
        context.update(self._context)
        return super(self.__class__, self).get_context_data(**context)


def settings_as_prop(name):
    ''' a wrapper to get setting in class '''
    def setting_get(self):
        obj, created = Setting.objects.get_or_create(name=name)
        return obj.value

    return property(setting_get)


class RSSFeed(Feed):
    title = settings_as_prop('blog_name')
    description = settings_as_prop('blog_desc')

    def link(self):
        return reverse('feed')

    def items(self):
        queryset = Blog.objects.all()
        return queryset.filter(status='public').order_by("-date_create")[0:8]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body_html

    def item_link(self, item):
        return item.get_absolute_url()

html/templates/admin.html
{% include "head.html" with title="Admin" only %}
<div class="container-fluid"><div class="row-fluid">
<div class="span2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">Posts</a></li>
    <li><a href="#">Comments</a></li>
    <li>
      <form action="{% url logout %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-warning" />
      </form>
    </li>
  <ul>
</div>
<div class="span10">
  <div><a href="{% url edit %}"><button class="btn btn-success">New Post</button></a></div>
  <table class="table">
  {% for object in object_list %}
    <tr>
      <td><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></td>
      <td><a href="{% url edit %}?pk={{ object.pk }}"><button class="btn btn-primary"><i class="icon-pencil icon-white"></i>  Edit</button></a><td>
    </tr>
  {% endfor %}
  </table>

  <div class="pagination">
  {% if is_paginated %}
    <ul>
    {% for index in paginator.page_range %}
      {% if index != page_obj.number %}
      <li ><a href="{% url admin %}?page={{index}}">{{ index }}</a></li>
      {% else %}
      <li class="disabled"><a href="#">{{ index }}</a></li>
      {% endif %}
    {% endfor %}
    </ul>
  {% endif %}
  </div>
</div>
</div></div>
{% include "foot.html" %}

html/templates/base.html
<!DOCTYPE HTML>
{% extends "common.html" %}
{% load static from staticfiles %}
{% load settings %}

{% block com_head %}
  <title> {% block title %}{% endblock %} -- {% get_setting "blog_name" %} </title>
  {% block head %}{% endblock %}
  <script>
    /* Google Analytics */
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '{% get_setting "google_analytics_id" %}']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
{% endblock %}

{% block com_body %}
<div class="blog-body wrapper">
  <div class="blog-head">
    <div class="navbar navbar-inverse blog-navbar wrapper">
      <div class="navbar-inner">
        <ul class="nav category-list">
          <li><a href="{% url home %}">Home</a></li>
          {% load category %}
          {% category_list as categorys %}
          {% for cat in categorys %}
          <li><a href="{% url category slug=cat.slug %}">{{ cat.name }}</a></li>
          {% endfor %}
        </ul>
        <ul class="nav" id="rss-link">
          <li><a href="{% url feed %}">RSS</a></li>
        </ul>
      </div>
    </div>
    <div class="hero-unit">
      <h1>{% get_setting "blog_name" %}</h1>
      <p></p>
      <p>{% get_setting "blog_desc" %}</p>
    </div>
  </div>

  <div class="blog-main">
    {% block content %}
    {% endblock %}
  </div>

  <div class="blog-foot">
    <div class="self-intro no-svg">
      <link href="{% static "plugins/webicons/webicons.css" %}" rel="stylesheet">
      <a class="webicon github large" target="blank" href="https://github.com/oneyoung">Github</a>
      <a class="webicon flickr large" target="blank" href="http://www.flickr.com/photos/oneyoung">Flickr</a>
      <a class="webicon douban large" target="blank" href="http://www.douban.com/people/oneyoung1988/">Douban</a>
      <a class="webicon instagram large" target="blank" href="http://instagram.com/oneyoung1988">Instagram</a>
      <a class="webicon zhihu large" target="blank" href="http://www.zhihu.com/people/oneyoung">Zhjihu</a>
      <a class="webicon linkedin large" target="blank" href="http://cn.linkedin.com/in/wayneguo/">LinkedIn</a>
      <a class="webicon googleplus large" target="blank" href="https://plus.google.com/u/0/+WayneGuo">Google+</a>
    </div>
    <div id="bottom">
      <h5>Created by <a href="https://github.com/oneyoung/django-blog">oneyoung</a> Powered by <a href="http://www.djangoproject.com/">Django</a><h5>
    </div>
  </div>
</div>

{% block script %}
{% endblock %}
<script type="text/javascript">
  /* Highlight.js */
  $.getScript('{% static "plugins/highlight.pack.js" %}', function() {
    hljs.tabReplace = '    ';  /* tab expand */
    /* we use <pre><code></code></pre> for code block */
    $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
  });
</script>
{% endblock %}

html/templates/blog.html
{% extends "base.html" %}
{% load settings %}
{% load static from staticfiles %}

{% block title %}{{ blog.title }}{% endblock %}

{% block head %}
<style>
  hr { margin-top: 0.5em }
  #album-cover { display: none}
</style>

<script type="text/javascript">
  function lightboxfy(img, group) { /* img is jQuery obj */
    var a = $('<a></a>')
    a.attr({
      'href': (img.attr('data-src')? img.attr('data-src'): img.attr('src')),
      'rel': 'lightbox[' + (group? '[' + group + ']': ''),
      'title': img.attr('alt'),
    });
    img.wrap(a);
  }
  function masonryfy(tag) {
    var div = $('<div class="item"></div>');
    $(tag).wrap(div);
    return div;
  }

  (function($) {
    $.fn.masonryFy = function(options) {
      var settings = $.extend({
        'column': 3,
        'selector': '.item',
      }, options);

      var _this = this;
      this.find('img').each(function () {
        var div = $('<div class="' + settings.selector.substr(1) + '"></div>');
        $(this).wrap(div);
        return div;
      });

      function resizeImage(cloumn) {
        var selector = _this.find(settings.selector);
        var marginWidth = selector.outerWidth(true) - selector.width();
        var width = _this.width()/settings.column - marginWidth*2;
        selector.each(function () {
          $(this).width(width);
        });
      }

      resizeImage();
      $(window).resize(resizeImage);

      this.imagesLoaded(function(){
        _this.masonry({
          itemSelector: settings.selector,
          isAnimated: true,
          columnWidth: function(containerWidth) {
            return containerWidth/3;
          },
        });
      });

      return this;
    }
  })(jQuery);

  $(window).load(function() {
    $('html body').animate({
      scrollTop: ($('#blog-text').offset().top - 50)
    }, 400);

    $('#goto-comments').click(function() {
      $('html body').animate({
        scrollTop: $('#disqus_thread').offset().top
      }, 400);
    });
    if ($('.content:has("img")').length) {
      loadCSS('{% static "plugins/lightbox2/lightbox.css" %}');
      $.getScript('{% static "plugins/lightbox2/lightbox.js" %}', function() {
        if ($('#album-images').length) { /* album */
          $.getScript('{% static "plugins/jquery.masonry.min.js" %}', function() {
            $('#album-images').masonryFy();
          });
          $('#album-images img').each(function() {
            lightboxfy($(this), 'album');
          });

          $.getScript('{% static "plugins/exif-js/binaryajax.js" %}');
          $.getScript('{% static "plugins/exif-js/exif.js" %}');
        } else {
          $('.content img').each(function() {
            lightboxfy($(this));
          });
        }
      });
    }
  });
</script>
{% endblock %}

{% block content %}
<div class="blog-block" id="blog-text">
  <div>
    <h1>{{ blog.title }}</h1>
    <p><i class="icon-calendar"></i> {{ blog.date_create|date:"o年n月j日" }}
    <span style="float: right" class="label btn" id="goto-comments"><i class="icon-comment"></i> Comments</span></p>
    <hr />
  </div>
  <div class="content">
    {% autoescape off %}
      {{ blog.body_html }}
    {% endautoescape %}
  </div>
  <div>
    <hr />
    <p style="margin-top: 1.5em"><i class="icon-tags"></i> {% for tag in blog.tags.all %}<a href="{% url tag tag=tag.name %}"><span class="label label-info">{{ tag }}</span></a> {% endfor %}</p>
  </div>
</div>

<div class="comment blog-block" id="disqus_thread">
  <script type="text/javascript">
    $(window).load(function () {
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = '{% get_setting "disqus_shortname" %}'; // required: replace example with your forum shortname

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    });
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
{% endblock %}

html/templates/edit.html
{% include "head.html" with title="Post Blog" only %}
<style type="text/css">
#id_title, table, textarea {
  width: 100%;
}

#id_post {
  float: right;
}

#id_table_tag td {
  width: 50%;
}
</style>
{% load bootstrap_toolkit %}
<form action="/admin/edit/?pk={{ pk }}" method="post" id="id_form_post" onsubmit="return submitPost()">
  {% csrf_token %}
  <table>
    <tr><td>
      <div><input name="title" type="text" id="id_title" maxlength="255"{% if not blog.title %} placeholder="Input your tilte here"{% else %}value="{{ blog.title }}"{% endif %} /></div>
    </td><tr>
    <tr><td>
      <div><textarea name="body_raw" rows=30 placeholder="Content of your blog">{% if blog.body_raw %}{{ blog.body_raw }}{% endif %}</textarea></div>
    </td><tr>
    <tr><td>
      {% for format in blog.RAW_FORMAT_CHOICES %}
      <label class="radio">
          <input type="radio" name="raw_format" value="{{ format.0 }}" {% if blog.raw_format == format.0 %}checked{% endif %}>{{ format.1 }}</input>
      </label>
      {% endfor %}
    </td><tr>
    <tr><td>
      <input name="tags" type="hidden" value="" />
      <button type="submit" id="id_post" class="btn btn-success">Post</button>
    </td><tr>
  </table>
</form>

<div id="id_table_tag">
      <input type="text" id="id_txt_tag" data-provide="typeahead" data-source='[{% for tag in tags %}"{{ tag }}",{% endfor %}""]' />
      <button class="btn" id="id_btn_addtag">Add</button>
      <div id="id_taglist">
      {% for tag in tags %}
        <span data-type="tag" class="label {% if blog.id and tag in blog.tags.all %} label-success{% endif %}" id="id_tag_{{ tag.name }}">{{ tag.name }}</span>
      {% endfor %}
      </div>
</div>


<script>
function createTag(name) {
  var tag = document.createElement("span");
  tag.setAttribute("data-type", "tag");
  tag.setAttribute("class", "label");
  tag.setAttribute("id", "id_tag_" + name);
  tag.textContent = name;
  return tag;
}

function selectTag(tag, select) {
  var SELECTED = "label label-success";
  var UNSELECTED = "label"
  if (select) {
    tag.setAttribute("class", SELECTED);
  } else {
    tag.setAttribute("class", UNSELECTED);
  }
}

function isTagSelected(tag) {
  return !(tag.getAttribute("class").search("success") < 0);
}

function toggleTag(tag) {
  if (isTagSelected(tag)) {
    selectTag(tag, false);
  } else {
    selectTag(tag, true);
  }
}

var tagList = document.getElementById("id_taglist");
tagList.onclick = function(event) {
  var tag = event.target;
  if (tag.getAttribute("data-type") == "tag") {
    toggleTag(tag);
  }
};

var addBtn = document.getElementById("id_btn_addtag");
addBtn.onclick = function(event) {
  var tagInput = document.getElementById("id_txt_tag");
  var name = tagInput.value
  if (name) {
    var tag = document.getElementById("id_tag_" + name);
    if (tag) {
      selectTag(tag, true);
    } else {
      var newTag = createTag(name);
      selectTag(newTag, true);
      document.getElementById("id_taglist").appendChild(newTag);
    }
    tagInput.value = ""
  }
};

function submitPost() {
  var form = document.getElementById("id_form_post");
  if (!form.elements["title"].value || !form.elements["body_raw"].value) {
    alert("Title and Content must not be blank!");
    return false
  }
  var allTags = document.getElementById("id_taglist").getElementsByTagName("span");
  var tags = [];
  for (var i = 0; i < allTags.length; i++) {
    var tag = allTags[i];
    if (isTagSelected(tag)) {
      tags[tags.length] = tag.textContent;
    }
  }
  form.elements["tags"].value = JSON.stringify(tags);
  form.submit();
  return true;
}

</script>
{% include "foot.html" %}