blogsite/urls.py
from django.conf.urls import patterns, url, include
from blog import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', views.BlogListView.as_view(), name='home'),
    url(r'^login/$', views.AdminLoginView.as_view(), name='admin_login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^admin/$', views.AdminView.as_view(), name='admin'),
    url(r'^admin/edit/$', views.EditView.as_view(), name='edit'),
    url(r'^admin/settings/$', views.SettingsView.as_view(), name='settings'),
    url(r'^admin/uploadimg/$', views.UploadImageView.as_view(), name='uploadimg'),
    url(r'^admin/imginfo/$', views.ImageInfoView.as_view(), name='imginfo'),
    url(r'^tag/(?P<tag>.+)/$',
        views.BlogListView.as_view(), name='tag'),
    url(r'^category/(?P<slug>.+)/$',
        views.BlogListView.as_view(), name='category'),
    url(r'^date/(?P<year>\d{4})(?P<month>\d{2})/$',
        views.BlogListView.as_view(), name='date'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>.+)/$',
        views.BlogView.as_view(), name='blog'),
    url(r'^feed/$', views.RSSFeed(), name='feed'),
    # Examples:
    # url(r'^$', 'blogsite.views.home', name='home'),
    # url(r'^blogsite/', include('blogsite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/django/', include(admin.site.urls), name='admin_django'),
)

from blogsite import settings
if hasattr(settings, 'DEBUG') and settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

blog/forms.py
# -*- coding: utf8 -*-
import json
from django import forms
from models import Blog, Category


class AdminUserForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.widgets.PasswordInput())


class BlogForm(forms.Form):
    title = forms.CharField(label='标题', max_length=255)
    body_raw = forms.CharField(label='正文', widget=forms.Textarea)
    raw_format = forms.ChoiceField(label='格式', choices=Blog.RAW_FORMAT_CHOICES)
    tags = forms.CharField(required=False, max_length=1024)
    status = forms.CharField(max_length=100)
    category = forms.CharField()

    def saveto(self, blog):
        blog.title = self.cleaned_data['title']
        blog.body_raw = self.cleaned_data['body_raw']
        blog.raw_format = self.cleaned_data['raw_format']
        blog.status = self.cleaned_data['status']

        tags_str = self.cleaned_data['tags']
        tags = json.loads(tags_str, encoding="utf8")
        blog.update_tags(tags)

        category = self.cleaned_data['category']
        blog.category = Category.objects.get(slug=category)

        blog.save()

html/templates/blog_admin/admin.html
{% extends "blog_admin/base.html" %}

{% block title %} Admin {% endblock %}

{% block content %}
<div class="container-fluid"><div class="row-fluid">
<div class="span2">
  <ul class="nav nav-pills nav-stacked">
    <li class="active"><a href="#">Posts</a></li>
    <li><a href="#">Comments</a></li>
    <li><a href="{% url settings %}">Settings</a></li>
    <li><a href="{% url admin %}django/">Django Admin Page</a></li>
    <li>
      <form action="{% url logout %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout" class="btn btn-warning" />
      </form>
    </li>
  <ul>
</div>
<div class="span10">
  <div><a href="{% url edit %}"><button class="btn btn-success">New Post</button></a></div>
  <table class="table" id="blog_list">
  {% for blog in object_list %}
    <tr>
      <td><span>{{ blog.status }}</span>   <a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></td>
      <td><a href="{% url edit %}?pk={{ blog.pk }}"><button class="btn btn-primary edit-btn" style="display:none"><i class="icon-pencil icon-white"></i>  Edit</button></a><td>
    </tr>
  {% endfor %}
  </table>

  <div class="pagination">
  {% if is_paginated %}
    <ul>
    {% for index in paginator.page_range %}
      {% if index != page_obj.number %}
      <li ><a href="{% url admin %}?page={{index}}">{{ index }}</a></li>
      {% else %}
      <li class="disabled"><a href="#">{{ index }}</a></li>
      {% endif %}
    {% endfor %}
    </ul>
  {% endif %}
  </div>
</div>
</div></div>
{% endblock %}

{% block src %}
<script>
window.onload = function() {
  $('#blog_list td:first-child span:first-child').map(function() {
    var type, val;
    switch($(this).text()) {
      case "public": type = "success"; val = "PUB"; break;
      case "draft": type = "warning"; val = "DFT"; break;
      case "private": type = "info"; val = "PRV"; break;
      case "delete": type = "important"; val = "DEL"; break;
    };
    $(this).text(val);
    $(this).addClass("label");
    $(this).addClass("label-" + type);
  });
};

$('#blog_list tr').hover(function () {
  $(this).find("button[class*='edit-btn']").css('display', '');
}, function() {
  $(this).find("button[class*='edit-btn']").css('display', 'none');
});
</script>
{% endblock %}

html/templates/blog_admin/base.html
<!DOCTYPE HTML>
{% extends "common.html" %}
{% load static from staticfiles %}

{% block com_head %}
  <title>{% block title %}Admin Page{% endblock %}</title>
  {% block head %}{% endblock %}
  <style>
  html body {
    background: white;
  }
  </style>
{% endblock %}

{% block com_body %}
<div class="container">
{% block content %}
{% endblock %}
</div>

{% block src %}
{% endblock %}

{% endblock %}

html/templates/blog_admin/edit.html
{% extends "blog_admin/base.html" %}

{% load static from staticfiles %}

{% block title %} Post Blog {% endblock %}

{% block head %}
<style type="text/css">
#id_title, table, textarea {
  width: 100%;
}

#id_submit {
  float: right;
}

#id_submit_choices button {
  width: 100%;
}

#id_table_tag td {
  width: 50%;
}

.image img {
  height: 100px;
  width: auto;
}

</style>
{% endblock %}

{% block content %}
{% load bootstrap_toolkit %}
<form action="/admin/edit/?pk={{ pk }}" method="post" id="id_form_post">
  {% csrf_token %}
  <table>
    <tr><td>
      <div><input name="title" type="text" id="id_title" maxlength="255"{% if not blog.title %} placeholder="Input your tilte here"{% else %}value="{{ blog.title }}"{% endif %} /></div>
    </td></tr>
    <tr><td>
      <div><textarea name="body_raw" id="id_body_raw" rows=30 placeholder="Content of your blog">{% if blog.body_raw %}{{ blog.body_raw }}{% endif %}</textarea></div>
      <div id="id_uploadimg" style="display:none">
        <table id="id_images">
          <tr class="image" style="display:none">
            <td><a class="delete-image">x</a></td>
            <td><input type="radio" name="cover-id" value="COVER_ID" /></td>
            <td><img /></td>
            <td>
              <div>
                <textarea></textarea>
              </div>
              <div class="progress progress-strip active">
                <div class="bar" style="width: 0%"></div>
              </div>
            </td>
          </tr>
        </table>
        <input type="file" multiple />
      </div>
    </td></tr>
    <tr><td>
      {% for format in blog.RAW_FORMAT_CHOICES %}
      <label class="radio">
          <input type="radio" name="raw_format" value="{{ format.0 }}" {% if blog.raw_format == format.0 %}checked{% endif %}>{{ format.1 }}</input>
      </label>
      {% endfor %}
    </td></tr>
    <tr><td>
      <label>Category:</label>
      <select name="category">
      {% for cat in category %}
        <option value="{{ cat.slug }}" {% if blog.category.slug == cat.slug %} selected {% endif %}>{{ cat.name }}</option>
      {% endfor %}
      </select>
    </td></tr>
    <tr><td>
      <input name="tags" type="hidden" value="" />
      <div class="btn-group" id="id_submit">
        <button class="btn dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" id="id_submit_choices">
          <li><button type="submit" name="status" value="public" class="btn btn-success">Post to Public</button></li>
          <li><button type="submit" name="status" value="draft" class="btn">Save as Draft</button></li>
          <li><button type="submit" name="status" value="private" class="btn btn-info">Private Only </button></li>
          <li><button type="submit" name="status" value="delete" class="btn btn-danger">Delete!</button></li>
        </ul>
      </div>
    </td></tr>
  </table>
</form>

<input type="file" id="id_fromfile" />

<div id="id_table_tag">
      <input type="text" id="id_txt_tag" data-provide="typeahead" data-source='[{% for tag in tags %}"{{ tag }}",{% endfor %}""]' />
      <button class="btn" id="id_btn_addtag">Add</button>
      <div id="id_taglist">
      {% for tag in tags %}
        <span data-type="tag" class="label {% if blog.id and tag in blog.tags.all %} label-success{% endif %}" id="id_tag_{{ tag.name }}">{{ tag.name }}</span>
      {% endfor %}
      </div>
</div>


{% endblock %}

{% block src %}
  <link rel="stylesheet" type="text/css" href="{% static "plugins/bootstrap/wysihtml5/bootstrap-wysihtml5-0.0.2.css" %}" />
  <script src="{% static "plugins/wysihtml5-0.3.0.min.js" %}"></script>
  <script src="{% static "plugins/bootstrap/wysihtml5/bootstrap-wysihtml5-0.0.2.min.js" %}"></script>

<script>
var selectedFlag = "label-success";

$('#id_taglist').delegate('span', 'click', function() {
  $(this).toggleClass(selectedFlag);
});

function addTag() {
  var name = $('#id_txt_tag').val();
  if (name) {
    var tag = $("#id_tag_" + name);
    if (tag.length) {
      tag.addClass(selectedFlag);
    } else {
      $('<span data-type="tag" class="label label-success" id="id_tag_#name">#name</span>'.replace(/#name/g, name)).appendTo("#id_taglist");
    }
    $('#id_txt_tag').val('');
  }
}

$('#id_txt_tag').keypress(function(e) {
  var code = (e.keyCode ? e.keyCode : e.which);
  if (code == 13) {
    addTag()
  }
});

$('#id_btn_addtag').click(addTag);

$("#id_form_post").submit(function () {
  $(this).find('input[name="title"], input[name="body_raw"]').each(function () {
    if (!$(this).val()) {
      alert("Title and Content must not be blank!");
      return false;
    }
  });
  var tags = $("#id_taglist").find("." + selectedFlag).map(function() {
    return $(this).text();
  });
  $(this).find('input[name="tags"]').each(function () {
    $(this).val(JSON.stringify($.extend(true, [], tags)));
  });
  if ($('input:radio[name="raw_format"]:checked').val() == 'album') {
    /* update image info before submit */
    var reqs = {};
    $('#id_images .image:visible').each(function () {
      var idx = $($(this).find('img')).attr('data-id');
      var desc = $($(this).find('textarea')).val();
      reqs[idx] = {'action': 'write', 'desc': desc};
    });
    $.ajax({
      type: 'POST',
      url: '{% url imginfo %}',
      data: JSON.stringify(reqs),
      success: function(data) {
        var resp = JSON.parse(data);
        for (var idx in resp) {
          var result = resp[idx];
          if (!result.status) {
            console.info('img ' + idx + ' fail, msg: ' + result.msg);
          }
        }
      },
      async: false, /* recv response before submit */
    });

    /* repack body_raw */
    wysihtml5Load(false);
    var body_raw = $('#id_body_raw');
    var divdesc = '<div id="album-desc">' + body_raw.val() + '</div>';
    var coverid = $('input[name="cover-id"]:checked').val();
    var divimgs = '<div id="album-images" data-cover="' + coverid + '">';
    $('#id_images img:visible').each(function () {
      $(this).attr('src', '');
      divimgs += $(this).prop('outerHTML');
    });
    divimgs += '</div>';
    body_raw.val(divdesc + divimgs);
  }
  return true;
});

function wysihtml5Load(load) {
  if (load) {
    $("#id_body_raw").wysihtml5({
      "html": true,
      "color": true,
      "stylesheets": ["{% static "plugins/bootstrap/wysihtml5/wysiwyg-color.css" %}"],
    });
  } else {
    textarea = $('#id_body_raw');
    textarea.siblings("*").each(function () {
      $(this).remove();
    });
    textarea.css('display', '');
  }
}

function albumLoad(load) {
  if (load) {
    /* disable format choice radio */
    $('input[name="raw_format"]').each(function() {
      if ($(this).val() != 'album') {
        $(this).attr('disabled', 'true');
      }
    });

    /* load raw and convert */
    var raw = $('<div>' + $('#id_body_raw').val() + '</div>');
    $('#id_body_raw').val($(raw.find('#album-desc')).html());
    wysihtml5Load(true);
    var reqs = {};
    $(raw.find('#album-images img')).each(function() {
      reqs[$(this).attr('data-id')] = {'action': 'read'};
    });
    var coverid = $(raw.find('#album-images')).attr('data-cover');
    $.post('{% url imginfo %}', JSON.stringify(reqs), function(data) {
      var resp = JSON.parse(data);
      for (var idx in resp) {
        var info = resp[idx];
        if (info.status) {
          var imgdiv = $('#id_uploadimg .image:first-child').clone();
          /* update img tag */
          var imgtag = $(imgdiv.find('img'));
          imgtag.attr('data-id', idx);
          imgtag.attr('src', info.thumb_url);
          imgtag.attr('alt', info.desc);
          /* update input:radio (cover-id) */
          var radio = $(imgdiv.find('input[name="cover-id"]'));
          radio.val(idx);
          if (coverid == idx) {
            radio.attr('checked', 'checked');
          }

          $(imgdiv.find('textarea')).val(info.desc);
          imgdiv.css('display', '');
          $(imgdiv.find('.progress')).css('display', 'none');
          imgdiv.appendTo('#id_images');
        } else {
          alert('Get image (ID' + idx +') info failed: ' + info.msg);
        }
      }
    });
    $('#id_uploadimg').css('display', '');
    $('#id_uploadimg').delegate('.delete-image', 'click', function() {
      if (confirm("Are you sure to delete?")) {
        var parentNode = $($(this).parents('.image'));
        var id = parentNode.find('img[data-id]').attr('data-id');
        var reqs = {};

        reqs[id] = {'action': 'del'};
        $.post('{% url imginfo %}', JSON.stringify(reqs), function(data) {
          parentNode.remove();
        });
      }
    });

    /* handling upload files */
    $('#id_uploadimg input').change(function() {
      $(this.files).map(function() {
        var type = /image\/.*/i;
        if (type.test(this.type)) {
          /* display upload file */
          var reader = new FileReader();
          var imgdiv = $('#id_uploadimg .image:first-child').clone();
          var imgtag = $(imgdiv.find('img'));
          reader.onload = function(e) {
            imgtag = $(imgdiv.find('img'));
            imgtag.attr('src', e.target.result);
            imgtag.attr('alt', this.name);
            imgdiv.css('display', '');
            imgdiv.appendTo('#id_images');
          };
          reader.readAsDataURL(this);

          /* upload file */
          var xhr = new XMLHttpRequest();
          xhr.fname = this.name;
          if (xhr.upload) {
            xhr.upload.onprogress = function (e) {
              var bar = $(imgdiv.find('.progress .bar'));
              var percentage = Math.floor((e.loaded/e.total*1000)/10) + '%';
              bar.css('width', percentage);
            };
          }
          xhr.onloadend = function(e) {
            if (xhr.status == 200) { /* ajax success */
              resp = JSON.parse(xhr.response)[xhr.fname];
              if (resp['status']) { /* upload success */
                imgtag.attr('data-id', resp.idx);
                $(imgdiv.find('input[name="cover-id"]')).val(resp.idx);
              }
            }
          };
          xhr.open('post', '{% url uploadimg %}', true);
          setCsrfToken(xhr);
          var fd = new FormData;
          fd.append(xhr.fname, this);
          xhr.send(fd);
        } else {
          alert(this.name + " is not an image file.");
        }
      });
    })
  } else {
    $('#id_uploadimg').css('display', 'none');
  }
}

$('#id_form_post input:radio').change(function() {
  var type = $(this).val();
  if (type == "html") {
    wysihtml5Load(true);
  } else {
    wysihtml5Load(false);
  }

  if (type == "album") {
    albumLoad(true);
  } else {
    albumLoad(false);
  }
});

window.onload = function () {
  /* Submit Button */
  $('#id_submit').prepend($('#id_submit_choices button[value="{{ blog.status }}"]').detach());
  var format = $('input[name="raw_format"]:checked').val();
  if (format == 'html') {
    /* bootstrap-wysihtml5 */
    wysihtml5Load(true);
  } else if (format == 'album') {
    albumLoad(true);
  }
};

$('#id_fromfile').change(function() {
  if (window.File && window.FileReader && window.FileList && window.Blob) {
    var reader = new FileReader();
    reader.readAsText(document.getElementById('id_fromfile').files[0]);
    reader.onload = function (evt) {
      $('#id_body_raw').val(evt.target.result);
    };
  } else {
    alert('The File APIs are not fully supported in this browser.');
  }
});
</script>
{% endblock %}

html/templates/blog_admin/login.html
{% extends "blog_admin/base.html" %}

{% block title %} Admin Login {% endblock %}

{% block content %}
<h1>Admin Login</h1>
{% load bootstrap_toolkit %}
<form action="/login/" method="post">
  {% csrf_token %}
  {{ form|as_bootstrap }}
  <input type="submit" value="Login" class="btn btn-success" />
</form>
{% if msg %}
<div class="alert alert-error"><strong>Error:</strong> {{ msg }}</div>
{% endif %}
{% endblock %}

html/templates/blog_admin/settings.html
{% extends "blog_admin/base.html" %}

{% block title %} setting {% endblock %}

{% block content %}
{% load settings %}
<form action="{% url settings %}" method="post">
  {% csrf_token %}
  {% get_options as options %}
  {% for option in options %}
  <label class="control-label" for="id_{{ option.name }}">{{ option.help }}</label>
  <div class="controls">
  <input id="id_{{ option.name }}" type="text" name="{{ option.name }}" value="{{ option.value }}" maxlength="100" />
  </div>
  {% endfor %}
  <input type="submit" value="OK" class="btn btn-success" />
</form>
{% endblock %}